name: C/C++ CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: cmake
      run: cmake .
    - name: make all targets
      run: make all

    - name: UT for BtsApplication
      run: make BtsApplicationUT 

    - name: Run BTS UTs
      run: ./BTS/Tests/Application/BtsApplicationUT

    - name: UT for COMMON
      run: make COMMON_UT

    - name: Run COMMON UTs
      run: ./COMMON/Tests/COMMON_UT

    - name: UT for UeApplication
      run: make UeApplicationUT

    - name: Run UE UTs
      run: ./UE/Tests/Application/UeApplicationUT

